#!/usr/bin/env python3

import random
import collections


NumberFormat = collections.namedtuple(
    'NumberFormat', ['name', 'from_str', 'to_str'])


NUMBER_FORMATS = [
    NumberFormat(name='Decimal',
                 from_str=lambda x: int(x, 10),
                 to_str=lambda x: format(x, 'd')),
    NumberFormat(name='Binary',
                 from_str=lambda x: int(x, 2),
                 to_str=lambda x: format(x, 'b')),
    NumberFormat(name='Hex',
                 from_str=lambda x: int(x, 16),
                 to_str=lambda x: format(x, 'x'))]


def ask(number, number_format):
    answer_str = input('{}: '.format(number_format.name))
    answer = number_format.from_str(answer_str)
    if answer != number:
        print('Wrong. {}'.format(number_format.to_str(number)))


def ask_random_nibble():
    nibble = random.randint(2, 15)
    format_to_show = random.choice(NUMBER_FORMATS)
    print('\n{}: {}'.format(
          format_to_show.name,
          format_to_show.to_str(nibble)))
    for number_format in NUMBER_FORMATS:
        if number_format != format_to_show:
            ask(nibble, number_format)


if __name__ == '__main__':
    try:
        while True:
            ask_random_nibble()
    except KeyboardInterrupt:
        print('\nGoodbye.')
