#!/usr/bin/env python3

import random
import collections


NumberFormat = collections.namedtuple(
    'NumberFormat', ['name', 'base', 'presentation_type'])


NUMBER_FORMATS = [NumberFormat(name='Decimal', base=10, presentation_type='d'),
                  NumberFormat(name='Binary', base=2, presentation_type='b'),
                  NumberFormat(name='Hex', base=16, presentation_type='x')]


def ask(nibble, number_format):
    answer_str = input('{}: '.format(number_format.name))
    answer = int(answer_str, number_format.base)
    if answer != nibble:
        print('Wrong. ' + format(nibble, number_format.presentation_type))


if __name__ == '__main__':
    while True:
        random_nibble = random.randint(1, 15)
        format_to_show = random.choice(NUMBER_FORMATS)
        print('\n' + format_to_show.name + ': ' +
              format(random_nibble, format_to_show.presentation_type))
        for number_format in NUMBER_FORMATS:
            if number_format != format_to_show:
                ask(random_nibble, number_format)
